### PR TITLE
update targeting/randomness to paper values

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by arnaudon** [comment]
I thought more test would have depended on that, but apparently no!

**Review by adrien-berchet — APPROVED** [review]
The previous values are no more relevant? Where did they come from?

**Comment by arnaudon** [comment]
they are outdated, these ones have been calibrated for synthesis paper. They are not used as the tmd_parameter.json is rarely made from this function, but it's better to have working values here, in case somebody wants to try this code without our home made .json files.

**Comment by adrien-berchet** [comment]
Ok I see, thanks

**Comment by arnaudon** [comment]
Sorry about the email spam, I was trying to see if I could merge with only one approval, but I can't. If it's ok with you @lidakanari , I'll just need your +2 to merge this one, thanks!

**Review by lidakanari — APPROVED** [review]
Sorry, forgot to approve this one. You can merge it.

**Pull request merged**
